# Generated by Django 3.0.4 on 2020-04-09 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('songs_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('singer', models.CharField(max_length=20)),
                ('songs_name', models.CharField(max_length=20)),
                ('song_file_url', models.CharField(max_length=80)),
                ('song_image_url', models.CharField(max_length=100)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicFile',
            fields=[
                ('songs_file_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('song_file', models.FileField(upload_to='music/musicfile', verbose_name='选择你的音乐')),
                ('song_image', models.ImageField(upload_to='image/sufimage', verbose_name='封面图')),
                ('IsDeleted', models.BooleanField(default=False)),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
