# Generated by Django 3.0.4 on 2020-04-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='MusicParentParam',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='MusicParentParamCode',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='music',
            name='MusicParentParamID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
