# Generated by Django 3.0.4 on 2020-04-17 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_music_musiccode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='MusicCode',
        ),
    ]
