# Generated by Django 3.0.4 on 2020-04-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_music_musiccode'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='MusicCode',
            field=models.CharField(default='', max_length=20),
        ),
    ]
